<class 'pandas.core.frame.DataFrame'>
RangeIndex: 624022 entries, 0 to 624021
Data columns (total 40 columns):
repo_id                                624022 non-null int64
url                                    624022 non-null object
language                               392569 non-null object
fork_count                             624022 non-null int64
stargazer_count                        624022 non-null int64
focal_class_identifier                 624022 non-null object
focal_class_superclass                 174443 non-null object
focal_class_interfaces                 239783 non-null object
focal_class_fields                     624022 non-null object
focal_class_methods                    624022 non-null object
focal_class_file                       624022 non-null object
focal_method_identifier                624021 non-null object
focal_method_parameters                624022 non-null object
focal_method_modifiers                 606006 non-null object
focal_method_return                    619463 non-null object
focal_method_body                      624022 non-null object
focal_method_signature                 624022 non-null object
focal_method_full_signature            624022 non-null object
focal_method_class_method_signature    624022 non-null object
focal_method_testcase                  624022 non-null bool
focal_method_constructor               624022 non-null bool
focal_method_invocations               624022 non-null object
test_class_identifier                  624022 non-null object
test_class_superclass                  103398 non-null object
test_class_interfaces                  3540 non-null object
test_class_fields                      624022 non-null object
test_class_file                        624022 non-null object
test_case_identifier                   623975 non-null object
test_case_parameters                   623579 non-null object
test_case_modifiers                    624022 non-null object
test_case_return                       624022 non-null object
test_case_body                         624022 non-null object
test_case_signature                    624022 non-null object
test_case_full_signature               624022 non-null object
test_case_class_method_signature       624022 non-null object
test_case_testcase                     624022 non-null bool
test_case_constructor                  624022 non-null bool
test_case_invocations                  624022 non-null object
focal_class_code                       0 non-null float64
test_class_code                        0 non-null float64
dtypes: bool(4), float64(2), int64(3), object(31)
memory usage: 173.8+ MB
None
<<<<<<<<<<<<<<<<<<<PART 1 FINISHED>>>>>>>>>>>>>>>>>>>>>>>>
<<<<<<<<<<<<<<<<<<<PART 2/5 FINISHED>>>>>>>>>>>>>>>>>>>>>>>>
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 0 entries
Empty DataFrameNone
<<<<<<<<<<<<<<<<<<<PART 2 FINISHED>>>>>>>>>>>>>>>>>>>>>>>>
Traceback (most recent call last):
  File "/home/saman.pordanesh/Large_Language_Models_in_RE/evaluator_model/.venv/lib64/python3.6/site-packages/pandas/core/indexes/base.py", line 2897, in get_loc
    return self._engine.get_loc(key)
  File "pandas/_libs/index.pyx", line 107, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/index.pyx", line 131, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/hashtable_class_helper.pxi", line 1607, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas/_libs/hashtable_class_helper.pxi", line 1614, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 'repo_id'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "De-anonymizing_Programmers_via_Code_Stylometry.py", line 171, in <module>
    desired_column = samplesdf.pop(column_name)
  File "/home/saman.pordanesh/Large_Language_Models_in_RE/evaluator_model/.venv/lib64/python3.6/site-packages/pandas/core/generic.py", line 862, in pop
    result = self[item]
  File "/home/saman.pordanesh/Large_Language_Models_in_RE/evaluator_model/.venv/lib64/python3.6/site-packages/pandas/core/frame.py", line 2995, in __getitem__
    indexer = self.columns.get_loc(key)
  File "/home/saman.pordanesh/Large_Language_Models_in_RE/evaluator_model/.venv/lib64/python3.6/site-packages/pandas/core/indexes/base.py", line 2899, in get_loc
    return self._engine.get_loc(self._maybe_cast_indexer(key))
  File "pandas/_libs/index.pyx", line 107, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/index.pyx", line 131, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/hashtable_class_helper.pxi", line 1607, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas/_libs/hashtable_class_helper.pxi", line 1614, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 'repo_id'
